# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15f99c7fed7951f8ae78db8dcdfdfc8ea4e5fafecc9a9e2b9fc25f3d4b74f4196f14fd42ca3dae018d882ae6d6ffa76516283c38c6cc70192bafad23623c50b4

test:
  secret_key_base: 30b73843976ccc5b698597941832b0bd925d2ff6683bee2df82d7636f348128e8cad0e340944a4a62ad93b2fb8289f57a63415470645364c7ba1a61917a11649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
